version: "3.8"

services:
    app:
        container_name: ${NODE_APP}
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        restart: unless-stopped
        ports:
            - ${PORT}:${PORT}
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - app-network

    # PostgreSQL Database
    postgres:
        image: postgres:17.6-alpine3.21
        container_name: ${DB_NAME}
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
