version: "3.8"

services:
    app:
        container_name: ${NODE_APP}
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        restart: unless-stopped
        ports:
            - "${PORT}:${PORT}"
        environment:
            - NODE_ENV=${NODE_ENV}
            - PORT=${PORT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
        depends_on:
            - postgres
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - dokploy-network
        labels:
            - traefik.enable=true
            - traefik.http.routers.${NODE_APP}.rule=Host(`cearlat.161.132.50.70`)
            - traefik.http.routers.${NODE_APP}.entrypoints=websecure
            - traefik.http.routers.${NODE_APP}.tls.certResolver=letsencrypt
            - traefik.http.services.${NODE_APP}.loadbalancer.server.port=${PORT}

    # PostgreSQL Database
    postgres:
        image: postgres:17.6-alpine3.21
        container_name: ${DB_NAME}
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - dokploy-network

volumes:
    postgres_data:

networks:
    dokploy-network:
        driver: bridge
