version: "3.8"

services:
    node-app:
        build:
            context: ./node-app
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - ./node-app:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev

    nginx:
        volumes:
            - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443" # Solo si necesitas SSL en desarrollo
